### ISSUE TITLE
[Warning] Deprecated: Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by scheinercc** [LeoColomb/pomo#16]
**Describe the bug**
Running WordPress 6.4.3 this PHP warning comes up:
```
Deprecated: Implicit conversion from float 4294967295 to int loses precision in /var/www/html/wp-includes/pomo/mo.php on line 208
```

**To Reproduce**
1. Run Wordpress 6.4.3
2. Switch on `WP_DEBUG` and `WP_DEBUG_DISPLAY`
3. Load the site
4. See warning printed out

**Expected behavior**
No warning being printed

**Actual behavior**
warning printed out

**Screenshots**
![image](https://github.com/LeoColomb/pomo/assets/817856/c9c0b24a-1b85-483e-8e54-4a17e688ab00)

**Versions**
The version running in WordPress 6.4.3

**Comment by LeoColomb** [comment]
Thanks for opening this issue @scheinercc.
That being said, the current POMO repository where you've just reported is not related to WordPress and is not maintained by any WordPress contributor.
Please report this issue to the WordPress community directly.
