### ISSUE TITLE
Question: NOOPTranslation class not loading

### ISSUE THREAD

**Issue by leogermani** [LeoColomb/pomo#5]
Hi,

Im starting using POMO in a php project. Im handling dependencies using composer autoload, and the calling "use POMO\MO" as suggested.

My problem is that the NOOPTranslations class is not beeing loaded. What is the right way to do it?

Thanks

**Comment by LeoColomb** [comment]
Hi @leogermani, thanks for your question.

> My problem is that the NOOPTranslations class is not beeing loaded

Is this a error thrown while you try to execute some script or a "personnal" requirement to work with `NOOPTranslations`?

In case of an error, please post the full report! 😺

**Comment by leogermani** [comment]
I was just replicating the WordPress approach into my application for a translation method. When the domain is not loaded, the method returns a noop object instead, I was doing the same. But when it happens, NOOPTranslation Class is not found.

Its actually pretty easy to change the approach and not use the NOOPTranslations class, Im just trying to understand this and do it the right way.

**Comment by LeoColomb** [comment]
Right, so this is an issue in your application, and not an issue of the POMO library at all.

> NOOPTranslation Class is not found

Actually, it still impossible for me to help you without the full error output.

---
```php
$translations = new MO();
if (!$translations->import_from_file($the_mo_filepath)) {
  $translations = new \POMO\Translations\NOOPTranslation();
}

$translations->translate($text)
```

**Comment by leogermani** [comment]
Thanks anyway, It helped! I didnt found a support channel. cheers.
